export const ingredientsList = [
  'Tuz', 'Karabiber', 'Zeytinyağı', 'Ayçiçek yağı', 'Tereyağı', 'Soğan', 'Sarımsak', 'Domates', 'Domates salçası',
  'Biber salçası', 'Kırmızı biber', 'Yeşil biber', 'Patates', 'Havuç', 'Kabak', 'Patlıcan', 'Salatalık', 'Limon',
  'Limon suyu', 'Maydanoz', 'Dereotu', 'Nane', 'Kekik', 'Pul biber', 'Kimyon', 'Sumak', 'Kuru nane', 'Defne yaprağı',
  'Biberiye', 'Taze fesleğen', 'Taze reyhan', 'Ispanak', 'Pazı', 'Marul', 'Roka', 'Tere', 'Kırmızı lahana', 'Beyaz lahana',
  'Karnabahar', 'Brokoli', 'Taze fasulye', 'Bakla', 'Bezelye', 'Nohut', 'Mercimek', 'Kuru fasulye', 'Barbunya', 'Pirinç',
  'Bulgur', 'Kuskus', 'Makarna', 'Un', 'Yufka', 'Lavaş', 'Ekmek', 'Tandır ekmeği', 'Pide', 'Simit', 'Pastırma', 'Sucuk',
  'Salam', 'Sosis', 'Tavuk', 'Kuzu eti', 'Dana eti', 'Kıyma', 'Balık', 'Hamsi', 'Sardalya', 'Levrek', 'Çipura', 'Kalamar',
  'Karides', 'Midye', 'Yumurta', 'Süt', 'Yoğurt', 'Ayran', 'Peynir', 'Beyaz peynir', 'Kaşar peyniri', 'Tulum peyniri', 'Lor peyniri',
  'Çökelek', 'Süzme yoğurt', 'Kaymak', 'Krema', 'Taze kayısı', 'Kuru kayısı', 'Kuru incir', 'Kuru üzüm', 'Ceviz', 'Fındık',
  'Badem', 'Fıstık', 'Antepfıstığı', 'Kabak çekirdeği', 'Ay çekirdeği', 'Susam', 'Çörek otu', 'Haşhaş tohumu', 'Bal', 'Pekmez',
  'Reçel', 'Marmelat', 'Şeker', 'Pudra şekeri', 'Esmer şeker', 'Bal kabağı', 'Nar', 'Elma', 'Armut', 'Üzüm', 'Şeftali', 'Kiraz',
  'Vişne', 'Kayısı', 'Erik', 'İncir', 'Karpuz', 'Kavun', 'Ayva', 'Portakal', 'Mandalina', 'Limon', 'Greyfurt', 'Muz', 'Çilek',
  'Böğürtlen', 'Ahududu', 'Yaban mersini', 'Frenk üzümü', 'Dut', 'Hindistancevizi', 'Hurma', 'Antep fıstığı', 'Kaju', 'Fıstık ezmesi',
  'Tahin', 'Helva', 'Lokum', 'Baklava', 'Kadayıf', 'Künefe', 'Revani', 'Şekerpare', 'Güllaç', 'Aşure', 'Keşkek', 'Mantı', 'Çiğ köfte',
  'İçli köfte', 'Kısır', 'Dolma', 'Sarma', 'Kuzu tandır', 'Adana kebap', 'Urfa kebap', 'İskender kebap', 'Döner', 'Lahmacun', 'Pide',
  'Börek', 'Su böreği', 'Gözleme', 'Katmer', 'Muhlama', 'Kaşarlı pide', 'Kıymalı pide', 'Tavuk şiş', 'Çöp şiş', 'Kuzu şiş', 'Ciğer',
  'Kokoreç', 'Uykuluk', 'Arnavut ciğeri', 'İşkembe', 'Paça', 'Tarhana',
];
